### ISSUE TITLE
Document breaking changes in 2.0

### ISSUE THREAD

**Issue by robb** [Mantle/Mantle#292]
Let's collect some of the more subtle stuff we need to document here, before we forget about it.

- [x] The direction of managed object transformers was reversed (d063837 #153)
- [x] Property mapping needs to be explicit (#170)
- [x] JSON mapping is implicitly validated (#251)
- [x] JSON key paths are restricted to `NSDictionaries` (#275)
- [x] Minimum deployment targets are 10.9 & 8.0
- [x] Core Data support has been extracted
- [x] `<MTLModel>` protocol extracted (#219)
- [x] Error handling in value transformers (#153)
- [x] JSON transformers on `MTLJSONAdapter` (#474)
- [x] Property storage behaviors (#210)

**Comment by robb** [comment]
Closed by #475
